daveg_security:
    resource: "@DavegSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

daveg_booking:
    resource: "@DavegBookingBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@DavegBookingBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout
