<?php

namespace Daveg\BookingBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends DocumentRepository
{
}
